<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>lims-control-lab-api-v0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="AspNetCore.HealthChecks.Npgsql" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LimsControlLab.Domain\LimsControlLab.Domain.csproj" />
    <ProjectReference Include="..\LimsControlLab.Infrastructure\LimsControlLab.Infrastructure.csproj" />
    <ProjectReference Include="..\LimsControlLab.SharedKernel\LimsControlLab.SharedKernel.csproj" />
  </ItemGroup>

</Project>
