// <auto-generated />
using System;
using LimsControlLab.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LimsControlLab.Infrastructure.Migrations
{
    [DbContext(typeof(LimsDbContext))]
    partial class LimsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateVersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TemplateVersionId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.AnalysisTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxTolerance")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinTolerance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Site")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("Site", "Name")
                        .IsUnique();

                    b.ToTable("AnalysisTemplates");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.AnalysisTemplateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalculationDefinitions")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxTolerance")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinTolerance")
                        .HasColumnType("numeric");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("TestConfiguration")
                        .HasColumnType("text");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique();

                    b.ToTable("AnalysisTemplateVersions");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AfterValues")
                        .HasColumnType("text");

                    b.Property<string>("BeforeValues")
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.CalibrationCurve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisTemplateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("AnalysisTemplateId", "Name")
                        .IsUnique();

                    b.ToTable("CalibrationCurves");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.CalibrationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalibrationCurveId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal>("XValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("YValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationCurveId", "Order")
                        .IsUnique();

                    b.ToTable("CalibrationPoints");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.ExceptionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<string>("DecisionComment")
                        .HasColumnType("text");

                    b.Property<int>("ReadingId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("ReadingId");

                    b.ToTable("ExceptionRecords");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Site")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Site", "Name")
                        .IsUnique();

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.IntegrationLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("AttemptedAtUtc");

                    b.HasIndex("TargetSystem", "Status");

                    b.ToTable("IntegrationLogs");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CalibratedValue")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CapturedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("InstrumentId")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ValidationResult")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("TestId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentSite")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Site")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisTemplateId");

                    b.HasIndex("Site", "Identifier")
                        .IsUnique();

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.SampleTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromSite")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer");

                    b.Property<int>("ToSite")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TransferredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransferredByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SampleId");

                    b.HasIndex("TransferredAtUtc");

                    b.ToTable("SampleTransfers");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.SamplingMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Site")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Site", "Name")
                        .IsUnique();

                    b.ToTable("SamplingMethods");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ExclusionRules")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecurrencePattern")
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("ShiftPattern")
                        .HasColumnType("integer");

                    b.Property<int>("Site")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Site", "Name")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Site")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.Sample", "Sample")
                        .WithMany()
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LimsControlLab.Domain.Entities.AnalysisTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LimsControlLab.Domain.Entities.AnalysisTemplateVersion", "TemplateVersion")
                        .WithMany()
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sample");

                    b.Navigation("Template");

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.AnalysisTemplate", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.AnalysisTemplateVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.AnalysisTemplateVersion", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.AnalysisTemplate", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.CalibrationCurve", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.AnalysisTemplate", "AnalysisTemplate")
                        .WithMany()
                        .HasForeignKey("AnalysisTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnalysisTemplate");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.CalibrationPoint", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.CalibrationCurve", "CalibrationCurve")
                        .WithMany("Points")
                        .HasForeignKey("CalibrationCurveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalibrationCurve");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.ExceptionRecord", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Exceptions")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LimsControlLab.Domain.Entities.Reading", "Reading")
                        .WithMany()
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.IntegrationLogEntry", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Reading", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Readings")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LimsControlLab.Domain.Entities.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Sample", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.AnalysisTemplate", "AnalysisTemplate")
                        .WithMany()
                        .HasForeignKey("AnalysisTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnalysisTemplate");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.SampleTransfer", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.Sample", "Sample")
                        .WithMany("Transfers")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("LimsControlLab.Domain.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.AnalysisTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.CalibrationCurve", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("LimsControlLab.Domain.Entities.Sample", b =>
                {
                    b.Navigation("Transfers");
                });
#pragma warning restore 612, 618
        }
    }
}
