<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LimsControlLab.Domain\LimsControlLab.Domain.csproj" />
    <ProjectReference Include="..\LimsControlLab.SharedKernel\LimsControlLab.SharedKernel.csproj" />
  </ItemGroup>

</Project>
